document.write("<EMBED ");
document.write("	type = \"application/x-java-applet\" \\ ");
document.write("   	CODE = \"RQDownloaderApp.class\" \\ ");
document.write("   	ARCHIVE = \"RQDownloaderApp.jar\" \\ ");
document.write("   	NAME = \"RQDownloaderApp\" \\ ");
document.write("   	WIDTH = \"100\" \\ ");
document.write("   	HEIGHT = \"100\" \\ ");
document.write(" 	scriptable = false \\ ");
document.write("  	pluginspage = \"http://java.sun.com/products/plugin/index.html#download\"> ");
document.write("   	<NOEMBED></NOEMBED> ");
document.write("</EMBED> ");