CREATE TABLE TND_FILE
(
 FLE_ID       VARCHAR(32),
 FLE_NAME     VARCHAR(255) NOT NULL,
 FLE_SIZE     INT(10) UNSIGNED,
 FLE_CRTDT    VARCHAR(14),
 FLE_MODDT    VARCHAR(14),
 FLE_STATUS	  VARCHAR(10) DEFAULT '0',
 FLE_MDID     SMALLINT(5) UNSIGNED NOT NULL,
 PRIMARY KEY (FLE_ID)
);
   
CREATE TABLE TND_MEDIA
(
 MD_ID       SMALLINT(5) UNSIGNED NOT NULL,
 MD_NAME     VARCHAR(255) NOT NULL,
 MD_TYPE     SMALLINT(5) UNSIGNED,
 MD_PATH     VARCHAR(255) NOT NULL,
 MD_CRTDT    VARCHAR(14),
 MD_DESC     VARCHAR(255),
 MD_MAXSIZE	 INT(10) UNSIGNED,
 MD_SIZE	 INT(10) UNSIGNED, 
 MD_VOLID    SMALLINT(5) UNSIGNED NOT NULL,
 PRIMARY KEY (MD_ID)
);

CREATE TABLE TND_VOLUME
(
 VOL_ID   	  SMALLINT(5) UNSIGNED NOT NULL,
 VOL_NAME     VARCHAR(255) NOT NULL,
 VOL_ACCESS   VARCHAR(10),
 VOL_CRTDT    VARCHAR(14),
 VOL_DESC     VARCHAR(255),
 PRIMARY KEY (VOL_ID)
);

CREATE TABLE TND_QUEUE
(
 QUE_FLE_ID   VARCHAR(32),
 QUE_TYPE     VARCHAR(10),
 QUE_CRTDT    VARCHAR(14),
 QUE_STATUS   VARCHAR(10),
 PRIMARY KEY (QUE_FLE_ID, QUE_TYPE)
);

CREATE TABLE TND_STAT
(
 STAT_ID      VARCHAR(10),
 STAT_TYPE    VARCHAR(10),
 STAT_CRTDT   VARCHAR(14),
 STAT_VALUE   VARCHAR(10),
 PRIMARY KEY (STAT_ID)
);