CREATE TABLE TND_VOLUME
(
 VOL_ID       NUMBER(5) NOT NULL, 
 VOL_NAME     VARCHAR(255) NOT NULL,
 VOL_ACCESS   VARCHAR(10),
 VOL_CRTDT    VARCHAR(14),
 VOL_DESC     VARCHAR(255),
 CONSTRAINT  VOLUME_PK PRIMARY KEY (VOL_ID) using index tablespace NDISC_X_TS
)  TABLESPACE NDISC_D_TS;


CREATE TABLE TND_MEDIA
(
 MD_ID       NUMBER(5) NOT NULL,    
 MD_NAME     VARCHAR(255) NOT NULL,
 MD_TYPE     NUMBER(5),
 MD_PATH     VARCHAR(255) NOT NULL,
 MD_CRTDT    VARCHAR(14),
 MD_DESC     VARCHAR(255),
 MD_MAXSIZE  NUMBER(12),
 MD_SIZE     NUMBER(12),
 MD_VOLID    NUMBER(5) CONSTRAINT MEDIA_VOLID_R REFERENCES TND_VOLUME(VOL_ID),
 CONSTRAINT  MEDIA_PK PRIMARY KEY (MD_ID) using index tablespace NDISC_X_TS
) TABLESPACE NDISC_D_TS;


CREATE TABLE TND_FILE
(
 FLE_ID       VARCHAR(32) NOT NULL,	
 FLE_NAME     VARCHAR(255) NOT NULL,
 FLE_SIZE     NUMBER(10),
 FLE_CRTDT    VARCHAR(14),
 FLE_MODDT    VARCHAR(14),
 FLE_STATUS   VARCHAR(10) DEFAULT '0',
 FLE_MDID     NUMBER(5) CONSTRAINT FILE_MDID_R REFERENCES TND_MEDIA(MD_ID),
 CONSTRAINT  FILE_PK PRIMARY KEY (FLE_ID) using index tablespace NDISC_X_TS
) TABLESPACE NDISC_D_TS;
  
   
CREATE TABLE TND_STAT
(
 STAT_ID      VARCHAR(10) NOT NULL,
 STAT_TYPE    VARCHAR(10),
 STAT_CRTDT   VARCHAR(14),
 STAT_VALUE   VARCHAR(10),
 CONSTRAINT  STAT_PK PRIMARY KEY (STAT_ID) using index tablespace NDISC_X_TS
) TABLESPACE NDISC_D_TS;


CREATE TABLE TND_QUEUE
(
 QUE_FLE_ID   VARCHAR(32),
 QUE_TYPE     VARCHAR(10),
 QUE_CRTDT    VARCHAR(14),
 QUE_STATUS   VARCHAR(10),
 CONSTRAINT  QUEUE_PK PRIMARY KEY (QUE_FLE_ID, QUE_TYPE) using index tablespace NDISC_X_TS
) TABLESPACE NDISC_D_TS;
